version: "3.9"  # Specify the Docker Compose file format version

services:
  go-rest-api:
    image: go-rest-api:latest  # Use the image created earlier
    build:
      context: .  # Build the image from the current directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 on the host to 8080 in the container
    environment:
      - ACCESS_SECRET=swapnil
      - REFRESH_SECRET=barai
    
